import { MarketTrendSkill } from "./types";

export const MARKET_TRENDS_DATA: MarketTrendSkill[] = [
  // Trending / Surging
  {
    skill: "Next.js & React 19",
    category: "Web & Cloud",
    growthRatePercentage: 64,
    activeOpeningsCount: 14820,
    averageSalaryLPA: 18.5,
    trendStatus: "Surging",
    marketInsight: "Rapid adoption by Indian unicorn startups transitioning to Server Components and edge rendering.",
  },
  {
    skill: "GenAI & LLM Orchestration",
    category: "AI & ML",
    growthRatePercentage: 182,
    activeOpeningsCount: 8940,
    averageSalaryLPA: 26.0,
    trendStatus: "Surging",
    marketInsight: "Extreme surge in demand for LangChain, vLLM, and agentic workflows in fintech and enterprise SaaS.",
  },
  {
    skill: "Go & Low-Latency Systems",
    category: "Languages",
    growthRatePercentage: 78,
    activeOpeningsCount: 6520,
    averageSalaryLPA: 24.2,
    trendStatus: "Surging",
    marketInsight: "Preferred replacement for heavy Java backend microservices in trading systems and payment gateways.",
  },
  {
    skill: "Rust & Systems Safety",
    category: "Languages",
    growthRatePercentage: 94,
    activeOpeningsCount: 2840,
    averageSalaryLPA: 28.0,
    trendStatus: "Surging",
    marketInsight: "High demand in infra, blockchain verification, and zero-allocation networking layers.",
  },
  {
    skill: "Kubernetes & Platform Ops",
    category: "Web & Cloud",
    growthRatePercentage: 42,
    activeOpeningsCount: 11200,
    averageSalaryLPA: 22.0,
    trendStatus: "Surging",
    marketInsight: "Core requirement for Tier-1 companies modernizing bare-metal to hybrid cloud environments.",
  },
  {
    skill: "FastAPI & Async Python",
    category: "Languages",
    growthRatePercentage: 55,
    activeOpeningsCount: 9400,
    averageSalaryLPA: 19.8,
    trendStatus: "Surging",
    marketInsight: "Standard backend bridge for high-speed ML inference pipelines and microservices.",
  },
  {
    skill: "PostgreSQL & Vector Extensions",
    category: "Web & Cloud",
    growthRatePercentage: 88,
    activeOpeningsCount: 8750,
    averageSalaryLPA: 21.5,
    trendStatus: "Surging",
    marketInsight: "pgvector superseding standalone vector DBs for cost-effective enterprise semantic search.",
  },

  // Steady
  {
    skill: "TypeScript",
    category: "Languages",
    growthRatePercentage: 28,
    activeOpeningsCount: 22100,
    averageSalaryLPA: 16.5,
    trendStatus: "Steady",
    marketInsight: "Universal baseline expectation across both frontend and backend enterprise engineering.",
  },
  {
    skill: "Docker Containerization",
    category: "Web & Cloud",
    growthRatePercentage: 19,
    activeOpeningsCount: 19300,
    averageSalaryLPA: 15.8,
    trendStatus: "Steady",
    marketInsight: "Foundational tool across all entry and mid-level software engineering openings.",
  },
  {
    skill: "Redis Distributed Caching",
    category: "Web & Cloud",
    growthRatePercentage: 24,
    activeOpeningsCount: 12400,
    averageSalaryLPA: 20.0,
    trendStatus: "Steady",
    marketInsight: "Critical requirement for session handling, idempotency, and pub/sub in high-scale systems.",
  },

  // Deprecating / Obsolete
  {
    skill: "jQuery & Vanilla DOM Scripting",
    category: "Legacy / Obsolete",
    growthRatePercentage: -48,
    activeOpeningsCount: 1200,
    averageSalaryLPA: 6.5,
    trendStatus: "Deprecating",
    marketInsight: "Legacy maintenance only. Almost zero new project adoptions in modern Indian tech firms.",
  },
  {
    skill: "PHP 5.x / LAMP Monolith",
    category: "Legacy / Obsolete",
    growthRatePercentage: -54,
    activeOpeningsCount: 2100,
    averageSalaryLPA: 7.2,
    trendStatus: "Deprecating",
    marketInsight: "Aggressive migration underway towards headless architectures and cloud-native services.",
  },
  {
    skill: "Adobe Flash / ActionScript",
    category: "Legacy / Obsolete",
    growthRatePercentage: -98,
    activeOpeningsCount: 10,
    averageSalaryLPA: 4.5,
    trendStatus: "Deprecating",
    marketInsight: "Completely phased out globally and excluded from modern browsers.",
  },
  {
    skill: "AngularJS (v1.x)",
    category: "Legacy / Obsolete",
    growthRatePercentage: -62,
    activeOpeningsCount: 850,
    averageSalaryLPA: 8.0,
    trendStatus: "Deprecating",
    marketInsight: "End-of-life reached; heavy risk liability in production enterprise banking apps.",
  },
  {
    skill: "SOAP XML Web Services",
    category: "Legacy / Obsolete",
    growthRatePercentage: -42,
    activeOpeningsCount: 1600,
    averageSalaryLPA: 9.5,
    trendStatus: "Deprecating",
    marketInsight: "Replaced by RESTful JSON, GraphQL, and high-performance gRPC contracts.",
  },
];
