import {
  BountyChallenge,
  CapstoneStudent,
  CertificateRecord,
  GitHubTelemetry,
  LetterOfRecommendation,
  PersonaProfile,
  SkillNode,
} from "./types";

export const DEMO_PERSONAS: PersonaProfile[] = [
  {
    id: "arjun-kumar",
    type: "student",
    name: "Arjun Kumar",
    title: "Pre-Final Year CSE Student",
    organization: "IIT Madras",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "priya-sharma",
    type: "recruiter",
    name: "Priya Sharma",
    title: "Senior Tech Recruiter",
    organization: "Razorpay Fintech India",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "dr-ramanathan",
    type: "faculty",
    name: "Dr. K. Ramanathan",
    title: "Head of Training & Placements",
    organization: "IIT Madras CSE Dept",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
  },
];

export const INITIAL_SKILLS: SkillNode[] = [
  {
    name: "TypeScript & React",
    category: "Frontend",
    score: 92,
    verified: true,
    evidenceCount: 4,
    sources: ["GitHub", "SkillCheck", "Bounty"],
  },
  {
    name: "Next.js App Router",
    category: "Frontend",
    score: 88,
    verified: true,
    evidenceCount: 3,
    sources: ["GitHub", "Bounty"],
  },
  {
    name: "Node.js & FastAPI",
    category: "Backend",
    score: 84,
    verified: true,
    evidenceCount: 3,
    sources: ["GitHub", "Certificate"],
  },
  {
    name: "PostgreSQL & Redis",
    category: "Database",
    score: 79,
    verified: true,
    evidenceCount: 2,
    sources: ["Certificate", "SkillCheck"],
  },
  {
    name: "Docker & Kubernetes",
    category: "Cloud/DevOps",
    score: 65,
    verified: true,
    evidenceCount: 2,
    sources: ["GitHub", "Certificate"],
  },
  {
    name: "PyTorch & GenAI",
    category: "AI/ML",
    score: 72,
    verified: true,
    evidenceCount: 2,
    sources: ["Certificate", "GitHub"],
  },
  {
    name: "Distributed Systems",
    category: "System Design",
    score: 60,
    verified: false,
    evidenceCount: 1,
    sources: ["Certificate"],
  },
];

export const INITIAL_GITHUB: GitHubTelemetry = {
  handle: "arjunkumar-dev",
  totalRepos: 34,
  starsCount: 142,
  contributionsThisYear: 847,
  topLanguages: [
    { name: "TypeScript", percentage: 48, color: "#3178c6" },
    { name: "Python", percentage: 28, color: "#3572A5" },
    { name: "Go", percentage: 14, color: "#00ADD8" },
    { name: "Rust", percentage: 10, color: "#dea584" },
  ],
  detectedStack: [
    "Next.js 15",
    "React 19",
    "FastAPI",
    "PostgreSQL",
    "Docker",
    "TailwindCSS",
    "Turborepo",
  ],
  devTier: "Advanced",
  verifiedAt: "2026-09-02T10:30:00Z",
  codeQualityScore: 91,
  recentActivity: [
    { repo: "fintech-idempotency-engine", commits: 14, message: "Add distributed lock with Redis redlock" },
    { repo: "rag-multimodal-docs", commits: 9, message: "Implement hybrid vector-bm25 reranking" },
    { repo: "next-sih-portal", commits: 22, message: "Optimize SSR caching and hydration passes" },
  ],
};

export const INITIAL_CERTIFICATES: CertificateRecord[] = [
  {
    id: "CERT-NPTEL-2025-9921",
    studentName: "Arjun Kumar",
    issuer: "NPTEL (IIT Madras)",
    courseTitle: "Design and Analysis of Algorithms",
    issueDate: "October 2025",
    verificationHash: "0x8fa4c3b99812eac1048b2d35cf81a073f1d2e5b9",
    confidenceScore: 98,
    status: "verified",
    tamperingFlags: [],
    skillsAwarded: ["Algorithms", "Complexity Analysis", "Data Structures"],
    rawMetadata: {
      producer: "NPTEL Digital Credential Engine v3.2",
      modifyDate: "2025-10-18T14:22:00Z",
      software: "NPTEL-Direct-Signer",
    },
  },
  {
    id: "CERT-AWS-2025-4108",
    studentName: "Arjun Kumar",
    issuer: "Amazon Web Services (AWS)",
    courseTitle: "AWS Certified Cloud Practitioner (CLF-C02)",
    issueDate: "December 2025",
    verificationHash: "0x3e18a994cba55198df5b32f1025a176881c3e0aa",
    confidenceScore: 95,
    status: "verified",
    tamperingFlags: [],
    skillsAwarded: ["Cloud Architecture", "AWS IAM", "VPC & S3"],
    rawMetadata: {
      producer: "Credly Acclaim PDF Producer",
      modifyDate: "2025-12-05T09:15:00Z",
      software: "Credly Digital Badge Engine",
    },
  },
  {
    id: "CERT-COURSERA-2026-114",
    studentName: "Arjun Kumar",
    issuer: "DeepLearning.AI / Coursera",
    courseTitle: "Deep Learning & Neural Networks Specialization",
    issueDate: "February 2026",
    verificationHash: "0x51b8ef091a457cba34856012ebca0792019ab3de",
    confidenceScore: 92,
    status: "verified",
    tamperingFlags: [],
    skillsAwarded: ["PyTorch", "Deep Learning", "Backpropagation"],
    rawMetadata: {
      producer: "Coursera Verification API",
      modifyDate: "2026-02-14T18:00:00Z",
      software: "Coursera PDF Certificate Generator",
    },
  },
];

export const INITIAL_BOUNTIES: BountyChallenge[] = [
  {
    id: "bounty-rzp-01",
    title: "Implement Idempotent Payment Webhook Dispatcher",
    company: "Razorpay",
    rewardINR: 15000,
    timeRemainingHours: 32,
    difficulty: "Hard",
    requiredSkills: ["Node.js", "Redis", "Idempotency Keys", "PostgreSQL"],
    description:
      "Design a production-grade webhook ingestion handler ensuring zero duplicate payouts even under concurrent network retries. Must utilize distributed redis locks and replay protection.",
    prSubmissionCount: 7,
    testChecklist: [
      "Handles 100 concurrent requests with same idempotency-key correctly",
      "Redis lock expiration gracefully recovers on worker crash",
      "Unit tests achieve >= 90% branch coverage",
    ],
    status: "Completed",
    submittedPrUrl: "https://github.com/razorpay/sandbox-challenges/pull/189",
    autoScorePreview: 96,
  },
  {
    id: "bounty-zerodha-02",
    title: "Zero-Allocation WebSocket Orderbook Parser in Go",
    company: "Zerodha Tech",
    rewardINR: 20000,
    timeRemainingHours: 18,
    difficulty: "Expert",
    requiredSkills: ["Go", "WebSockets", "Low Latency", "Ring Buffers"],
    description:
      "Process 50,000 tick/sec market data stream with zero heap allocations per tick. Parse binary Kite Connect protocol into structured DOM depth tables.",
    prSubmissionCount: 4,
    testChecklist: [
      "Benchmark allocations: 0 B/op on benchmark suite",
      "Latency p99 < 15 microseconds per packet",
      "Graceful disconnect and ring-buffer draining",
    ],
    status: "Open",
  },
  {
    id: "bounty-phonepe-03",
    title: "Distributed Rate Limiter with Leaky Bucket & Slotted Windows",
    company: "PhonePe",
    rewardINR: 12000,
    timeRemainingHours: 42,
    difficulty: "Intermediate",
    requiredSkills: ["Redis", "Distributed Systems", "TypeScript"],
    description:
      "Create an Express/Fastify middleware implementing multi-tier tenant rate limits across 3 Redis cluster shards with sub-millisecond overhead.",
    prSubmissionCount: 11,
    testChecklist: [
      "Lua script atomic token consumption across distributed nodes",
      "Slotted sliding window prevents boundary burst attacks",
      "Returns RFC-standard 429 headers: X-RateLimit-Reset, Retry-After",
    ],
    status: "Open",
  },
  {
    id: "bounty-hasura-04",
    title: "GraphQL Sub-Graph AST Cache Invalidator",
    company: "Hasura",
    rewardINR: 18000,
    timeRemainingHours: 24,
    difficulty: "Hard",
    requiredSkills: ["GraphQL", "Rust", "Cache Architecture"],
    description:
      "Analyze inbound mutation ASTs to determine affected query cached roots and publish targeted eviction messages over NATS stream.",
    prSubmissionCount: 5,
    testChecklist: [
      "Correct dependency graph generation for nested entities",
      "Zero false-positive cache purges on irrelevant fields",
      "NATS pub/sub benchmark throughput verified",
    ],
    status: "Open",
  },
];

export const INITIAL_LORS: LetterOfRecommendation[] = [
  {
    id: "LOR-IITM-2026-081",
    studentName: "Arjun Kumar",
    studentId: "CS23B044",
    college: "Indian Institute of Technology, Madras",
    evaluatorName: "Dr. K. Ramanathan",
    evaluatorTitle: "Professor & Placements Faculty Advisor",
    companyOrDept: "Department of Computer Science and Engineering",
    metricRatings: {
      technicalProficiency: 5,
      systemArchitecture: 5,
      problemSolving: 5,
      communicationCollab: 4,
      innovationInitiative: 5,
    },
    recommendationBody:
      "Arjun has demonstrated exceptional mastery over scalable web architectures and algorithmic optimization during his research capstone. He single-handedly redesigned our department's distributed lab scheduler, cutting latency by 74%. His adherence to clean code, cryptographic security principles, and peer mentoring places him firmly in the top 2% of engineering talent I have supervised.",
    issuedAt: "2026-03-01T12:00:00Z",
    cryptographicHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    verificationBadgeToken: "SKILLNEXUS-IITM-VRF-8819",
  },
];

export const CAPSTONE_PEERS: CapstoneStudent[] = [
  {
    id: "peer-01",
    name: "Arjun Kumar",
    college: "IIT Madras",
    primaryRole: "Backend Engineer",
    verifiedSkills: ["FastAPI", "PostgreSQL", "Redis", "Distributed Systems", "Docker"],
    readinessScore: 89,
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "peer-02",
    name: "Ananya Deshmukh",
    college: "BITS Pilani",
    primaryRole: "Frontend Engineer",
    verifiedSkills: ["Next.js 15", "React 19", "TailwindCSS", "WebGL", "TypeScript"],
    readinessScore: 93,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "peer-03",
    name: "Rohan Varma",
    college: "NIT Trichy",
    primaryRole: "AI/ML Specialist",
    verifiedSkills: ["PyTorch", "Hugging Face", "LangChain", "Vector DBs", "RAG"],
    readinessScore: 86,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "peer-04",
    name: "Sneha Nair",
    college: "VIT Vellore",
    primaryRole: "Cloud & DevOps",
    verifiedSkills: ["Kubernetes", "Terraform", "AWS", "CI/CD Actions", "Prometheus"],
    readinessScore: 84,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "peer-05",
    name: "Tanmay Bansal",
    college: "DTU Delhi",
    primaryRole: "UI/UX Designer",
    verifiedSkills: ["Design Systems", "Figma", "Micro-interactions", "User Research", "CSS Animation"],
    readinessScore: 88,
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "peer-06",
    name: "Meera Iyer",
    college: "IIIT Hyderabad",
    primaryRole: "Backend Engineer",
    verifiedSkills: ["Go", "gRPC", "Kafka", "PostgreSQL", "System Architecture"],
    readinessScore: 91,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200",
  },
];

export const INTERNSHIP_LISTINGS = [
  {
    id: "intern-rzp-01",
    title: "Backend Platform Engineer Intern",
    company: "Razorpay",
    location: "Bengaluru, Karnataka (Hybrid)",
    stipendINR: 65000,
    duration: "6 Months",
    requiredSkills: ["Node.js & FastAPI", "PostgreSQL & Redis", "Distributed Systems", "Docker & Kubernetes"],
    preferredSkills: ["Go", "Kafka", "Idempotency Design"],
    description: "Build high-scale financial pipes handling $100B+ TPV with zero tolerance for state inconsistencies.",
    minReadinessScore: 80,
  },
  {
    id: "intern-phonepe-02",
    title: "Full Stack Infrastructure Intern",
    company: "PhonePe",
    location: "Bengaluru (On-site)",
    stipendINR: 70000,
    duration: "6 Months",
    requiredSkills: ["TypeScript & React", "Next.js App Router", "Node.js & FastAPI", "Docker & Kubernetes"],
    preferredSkills: ["Redis", "Distributed Caching", "Microservices"],
    description: "Develop merchant reconciliation and high-throughput real-time telemetry dashboards.",
    minReadinessScore: 78,
  },
  {
    id: "intern-swiggy-03",
    title: "Applied AI & RAG Systems Intern",
    company: "Swiggy",
    location: "Bengaluru (Remote)",
    stipendINR: 60000,
    duration: "4 Months",
    requiredSkills: ["PyTorch & GenAI", "TypeScript & React", "PostgreSQL & Redis"],
    preferredSkills: ["Vector Embeddings", "vLLM", "Prompt Optimization"],
    description: "Engineer dynamic food discovery bots and multimodal menu translation engines.",
    minReadinessScore: 75,
  },
  {
    id: "intern-zerodha-04",
    title: "Core Trading Systems Engineering Intern",
    company: "Zerodha",
    location: "Bengaluru (On-site)",
    stipendINR: 80000,
    duration: "6 Months",
    requiredSkills: ["Distributed Systems", "PostgreSQL & Redis", "Docker & Kubernetes"],
    preferredSkills: ["Go", "Zero Allocation Caching", "Low-Latency Networks"],
    description: "Tackle millisecond order execution pipelines and fault-tolerant settlement ledgers.",
    minReadinessScore: 85,
  },
];
